---
abstract: 'Mojolicious Plugin'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: 0.025
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.3, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-GoogleAnalytics
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
resources:
  bugtracker: https://github.com/battlemidget/Mojolicious-Plugin-GoogleAnalytics/issues
  homepage: https://github.com/battlemidget/Mojolicious-Plugin-GoogleAnalytics
  repository: https://github.com/battlemidget/Mojolicious-Plugin-GoogleAnalytics.git
version: 1.003
x_contributors:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
