---
abstract: 'Mojolicious plugin for integrating Google Analytics'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-GoogleAnalytics
requires:
  Mojo::Base: 0
  strictures: 1
resources:
  homepage: https://github.com/battlemidget/Mojolicious-Plugin-GoogleAnalytics
  repository: https://github.com/battlemidget/Mojolicious-Plugin-GoogleAnalytics.git
version: 0.003
